In [1]:
%load_ext autoreload
%autoreload 2

In [133]:
from nba_api.stats.endpoints.teamdetails import TeamDetails
from nba_api.stats.endpoints.boxscoresummaryv2 import BoxScoreSummaryV2
from nba_api.stats.endpoints.commonplayerinfo import CommonPlayerInfo
from basketball_db.utils import get_proxies, combine_team_games
import pandas as pd
from basketball_db.extract import get_box_score_summaries

In [134]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [ ]:
dfs = CommonPlayerInfo(['203999, 2544']).get_data_frames()

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

IndexError: list index out of range

In [131]:
dfs = BoxScoreSummaryV2('0021701171').get_data_frames()
for df in dfs:
    df.columns = df.columns.to_series().apply(lambda x: x.lower())
df = pd.merge(dfs[1], dfs[1], suffixes=['_home', '_away'], on='league_id')
df = pd.DataFrame(df[df.team_id_home != df.team_id_away].iloc[0, :]).T.drop(['team_id_home', 'team_id_away'], axis=1).reset_index(drop=True)
temp = pd.concat([df, dfs[0], dfs[4]], axis=1)
temp

,league_id,team_abbreviation_home,team_city_home,pts_paint_home,pts_2nd_chance_home,pts_fb_home,largest_lead_home,lead_changes_home,times_tied_home,team_turnovers_home,total_turnovers_home,team_rebounds_home,pts_off_to_home,team_abbreviation_away,team_city_away,pts_paint_away,pts_2nd_chance_away,pts_fb_away,largest_lead_away,lead_changes_away,times_tied_away,team_turnovers_away,total_turnovers_away,team_rebounds_away,pts_off_to_away,game_date_est,game_sequence,game_id,game_status_id,game_status_text,gamecode,home_team_id,visitor_team_id,season,live_period,live_pc_time,natl_tv_broadcaster_abbreviation,live_period_time_bcast,wh_status,game_date,attendance,game_time
0,00,TOR,Toronto,54,12,12,20,8,2,1,11,8,14,BOS,Boston,34,10,9,6,8,2,1,17,8,29,2018-04-04T00:00:00,4,0021701171,3,Final,20180404/BOSTOR,1610612761,1610612738,2017,4,,ESPN,Q4 - ESPN,1,"WEDNESDAY, APRIL 4, 2018",19963,2:10

In [41]:
dfs = get_box_score_summaries('0021701171)

      team_id        city    nickname  year_founded  year_active_till
0  1610612737     Atlanta       Hawks          1968              2019
1  1610612737   St. Louis       Hawks          1955              1967
2  1610612737   Milwaukee       Hawks          1951              1954
3  1610612737  Tri-Cities  Blackhawks          1949              1950

In [42]:
dfs[3]

TEAM_ID                  TEAM_ID
CITY                        CITY
NICKNAME                NICKNAME
YEARFOUNDED          YEARFOUNDED
YEARACTIVETILL    YEARACTIVETILL
dtype: object

In [112]:
dfs[4]

                  game_date  attendance game_time
0  WEDNESDAY, APRIL 4, 2018       19963      2:10

In [132]:
dfs[5]

,game_date_est,game_sequence,game_id,team_id,team_abbreviation,team_city_name,team_nickname,team_wins_losses,pts_qtr1,pts_qtr2,pts_qtr3,pts_qtr4,pts_ot1,pts_ot2,pts_ot3,pts_ot4,pts_ot5,pts_ot6,pts_ot7,pts_ot8,pts_ot9,pts_ot10,pts
0,2018-04-04T00:00:00,4,0021701171,1610612761,TOR,Toronto,Raptors,56-22,14,29,24,29,0,0,0,0,0,0,0,0,0,0,96
1,2018-04-04T00:00:00,4,0021701171,1610612738,BOS,Boston,Celtics,53-25,20,13,20,25,0,0,0,0,0,0,0,0,0,0,78